### ISSUE TITLE
no websocket api for spot trading and poor english

### ISSUE THREAD

**Issue by proxychainio** [bithumb-pro/bithumb.pro-official-api-docs#1]
no websocket api for spot trading, and so many mismatches between the document and the code. For example, the doc didn't mention bizCode while this field is required.. The API sucks,  and the webpage lags, you have lots of work to do.

**Comment by godlikers** [comment]
first at all, sorry, we actually need do a lot of work for upgrade the doc and api, the bizCode is not required for new api, we will upgrade the code.  the Websocket API for spot trading is  https://github.com/bithumb-pro/bithumb.pro-official-api-docs/blob/master/ws-api.md, you can find simple demo in  https://github.com/bithumb-pro/java-api-client.

**Comment by proxychainio** [comment]
No, the websocket API  docs you mentioned are all about CONTRACT.

**Comment by godlikers** [comment]
the Websocket API use topic(contain SPOT and CONTRACT). for example, the SPOT topic like TICKER:BTC-USDT, the CONTRACT topic like CONTRACT_TICKER:TBTCUSD

**Comment by proxychainio** [comment]
I also guessed they're identical and tried to subscribe spot order updates, I've  sent {"cmd":"subscribe","args":["ORDER"]} (tried SPOT_ORDER also)after auth, but server returned to me {"code":"10005","msg":"No topic"}. After that I'm really disappointed and give up...
