### ISSUE TITLE
Could I know where your server located

### ISSUE THREAD

**Issue by jflyup** [bithumb-pro/bithumb.pro-official-api-docs#12]
I'm running my crypto trading algo on vps located in Japan, but the latency to bithumb.pro is about 500ms. I noticed your server's IP is in US. If i wanna reduce the network latency, where should I place my VPS?

**Comment by SergeyLeshchinskiy** [comment]
I'm running my crypto trading algo on vps located in USA, but the latency to bithumb.pro is about 700ms. I noticed your server's IP is in US. If i wanna reduce the network latency, where should I place my VPS?
