### ISSUE TITLE
Some issue with api call

### ISSUE THREAD

**Issue by ruiwang-quant** [bithumb-pro/bithumb.pro-official-api-docs#16]
trying following url: https://global-openapi.bithumb.pro/openapi/v1/spot/assetList

with request body
{
	"apiKey" : "xxxx",
	"assetType": "spot",
	"timestamp":1569596006874,
	"version":"v1.0.0",
	"signature": "xxxxx"
}

keep getting response
{
    "data": null,
    "code": "9002",
    "msg": "verifySignature failed",
    "timestamp": 1569596017901
}

Could you give an example of signing process with sample api key and secret key please. I could compare my signing process.

**Comment by godlikers** [comment]
check your presignature string,all request params must be sort by dict and join with &amp; except to signature.
eg:
presignature =apiKey=xxx&amp;assetType=spot&amp;timestamp=xxx&amp;version=xxx&amp;signature

---Original---

**Comment by ruiwang-quant** [comment]
thanks for the reply.

i have found the issue. the signature in hex need to be in lowercase only. mine was in UPPERCASE, and server reject the request because of the case. maybe it's a good idea to mention in the document that "signature needs to be in lowercase"

thanks for the help

**Comment by godlikers** [comment]
thanks for advice.



---Original---

**Comment by webcaetano** [comment]
Hi Guys.

Had same issue. 
And some other "trial and errors" until succeed. 

Here's piece of feedback:
- The docs does not say if is hex or base64 (thanks @ruiwang-quant)
- The docs also not say if the parameters need to be in alphabetic order (it does) (with screwed me for a while) 
- Some timestamps on the docs have 14 digits (correct are 13)
- Some versions in docs are in upper case "V1.0.0" and some lowercase "v1.0.0" , it does not matter, but docs does not specify. Kinda miss lead if this was the error.

**Comment by godlikers** [comment]
thanks for your comment @webcaetano . we will check and fix it in the docs.
