### ISSUE TITLE
verifySignature failed

### ISSUE THREAD

**Issue by lincvv** [bithumb-pro/bithumb.pro-official-api-docs#18]
following url: https://global-openapi.bithumb.pro/openapi/v1/spot/assetList

same problem(https://github.com/bithumb-pro/bithumb.pro-official-api-docs/issues/16), everything is lowercase 

apiKey=XXX&assetType=spot&timestamp=1572362450281&version=v1.0.0

hmac.new(byte_key, query_string.encode('utf-8'), hashlib.sha256).hexdigest().lower()

body:
data = {
'apiKey': API_KEY,
'assetType': 'spot',
'timestamp': timestamp,
'version': 'v1.0.0'
'signature': signature
}
{"data":null,"code":"9002","msg":"verifySignature failed","timestamp":1572362451236}

**Comment by bithumb-pro** [comment]
you can use the demo(https://github.com/bithumb-pro/python-api-client/blob/master/BithumbGlobal.py).try it.

**Comment by lincvv** [comment]
Thanks
