### ISSUE TITLE
What's the type of timestamp in websocket auth command exactly?

### ISSUE THREAD

**Issue by proxychainio** [bithumb-pro/bithumb.pro-official-api-docs#2]
The doc said it was int, then it's string now, the so-called sample code which never worked showed it's int. I've tried then all, none works. This exchange is in choas.

**Comment by godlikers** [comment]
the type timestamp is string.

**Comment by godlikers** [comment]
this is bug for so-called sample code in java, i will fix it. and upgrade doc. thank you!
