### ISSUE TITLE
NodeJs 에서 verifySignature 관련 문의요

### ISSUE THREAD

**Issue by mecon-coin** [bithumb-pro/bithumb.pro-official-api-docs#20]
NodeJs로 api 연동 중입니다.
spot/assetList 을 구현하는데요.
아래와 같이 리턴이 옵니다.
{"data":null,"code":"9002","msg":"verifySignature failed","timestamp":1573531933385}

Signature 구하는 코드 입니다. 아래 코드에서 수정되어야 될 부분을 알려주세요

  let currTime = Date.now();
  let param = {
    "apiKey" : APIKEY,
    "timestamp" : currTime,
    "msgNo" : currTime,
    "assetType" : "spot",
  }
 let fromParam = `apiKey=${APIKEY}&timestamp=${currTime}&msgNo=${currTime}&assetType=spot`;
let signature = CryptoJS.HmacSHA256(fromParam, APISECRET).toString(CryptoJS.enc.Hex)
param['signature'] = signature;

감사합니다.

**Comment by godlikers** [comment]
your fromParam is error, should be fromParam =  apiKey=${APIKEY}&assetType=spot&msgNo=${currTime}&timestamp=${currTime};
fromParam need do sort by dict.

**Comment by mecon-coin** [comment]
해결돼었습니다.
