### ISSUE TITLE
20053 error

### ISSUE THREAD

**Issue by Ppantich** [bithumb-pro/bithumb.pro-official-api-docs#23]
How to solve 20053 error when place order? What and where I should sign? Explain, do not just close the issue.

**Comment by Ppantich** [comment]
How I created API keys without signing in Bithumb global? Though I am signed via Bithumb account.

**Comment by godlikers** [comment]
if place order at first time, need to sign in bithumb global website at trade page.


---Original---

**Comment by Ppantich** [comment]
OK, for trading GEM pairs need to place order in the web and sign service agreement. Solved.
