### ISSUE TITLE
missing spot order updates via websocket

### ISSUE THREAD

**Issue by proxychainio** [bithumb-pro/bithumb.pro-official-api-docs#3]
I've subed the private topic ORDER, when a order is finished, no updates received. Moreover, it discards order updates (randomly? I don't know). You guys push me to spam the `orderDetail` REST API, then ban me for too many requests. Do you guys test the API completely? Let traders do the testing work for you?

**Comment by godlikers** [comment]
i will check for this as soon as fast.

**Comment by godlikers** [comment]
sorry, we had a bug and had fixed.

**Comment by proxychainio** [comment]
Thanks for the quick response. Another problem is order update from websocket delayed too much(>1s) than polling via REST API.

**Comment by godlikers** [comment]
we need upgrade the system recently.

**Comment by proxychainio** [comment]
Thanks, hope everything goes well.
