### ISSUE TITLE
9002 on spot placeOrder 

### ISSUE THREAD

**Issue by CyberSensei1** [bithumb-pro/bithumb.pro-official-api-docs#32]
I am getting 9002 "verifySignature failed" error on spot/placeOrder i can run spot/openOrders without any error but in placeOrder i am getting error. I cant find whereis the error. I am using C# for doing this.

My string for sign on placeOrder :
`apiKey=MyApiKey&msgNo=1582571405503&symbol=CZZ-USDT&type=limit&side=buy&price=0.01&quantity=100&timestamp=1582571405503&version=v1.0.0`

MyJson for placeOrder :
`{"apiKey":"MyApiKey",
  "msgNo":"1582571405503",
   "symbol":"CZZ-USDT",
   "type":"limit",
   "side":"buy",
   "price":"0.01",
   "quantity":"100",
   "timestamp":1582571405503,
   "version":"v1.0.0",
   "signature":"HMACSHA256lowercaseHexOfStringAbove"}`

my string for sign on openOrders :
`apiKey=MyApiKey&msgNo=1582571796956&symbol=CZZ-USDT&timestamp=1582571796956&version=v1.0.0`

My json for openOrders :
`{"apiKey":"MyApiKey","msgNo":"1582571796956","symbol":"CZZ-USDT","timestamp":1582571796956,"version":"v1.0.0","signature":"HMACSHA256lowercaseHexOfStringAbove"}`

**Comment by godlikers** [comment]
request params should in alphabetic order，like “a=xxx&b=xxx&c=xxx&d=xxx”

**Comment by CyberSensei1** [comment]
Gotcha ! Yeap its working now thanks.
