### ISSUE TITLE
How to withdraw USDT via ERC20 chain using API?

### ISSUE THREAD

**Issue by easondongsh** [bithumb-pro/bithumb.pro-official-api-docs#34]
How to fill in the parameters?
When I try to withdraw usdt, it always response error code "20038"

**Comment by godlikers** [comment]
may be your withdrawal address not valid.

**Comment by easondongsh** [comment]
no, the address is right, but I can not withdraw usdt via API.
I don't know how to fill parameters of withdraw api, which parameter stands for usdt-chain (erc20)
please help me

**Comment by easondongsh** [comment]
Can anyone help me? please!

**Comment by godlikers** [comment]
can you show me your request params？

**Comment by easondongsh** [comment]
I just used python3 sdk provided by bithumb global.
I revoke method named "withdraw" 
withdraw ("USDT",my_withdraw_address, 100) , and the response is   [20038] withdrawal address is not valid

**Comment by easondongsh** [comment]
params is :
{
            'coinType': "usdt",
            'address': my_address,
            'quantity': 100,
            'mark': 'AUTO'
        }
just like this

**Comment by easondongsh** [comment]
I just used python3 sdk provided by bithumb global.
I revoke method named "withdraw"
withdraw ("USDT",my_withdraw_address, 100) , and the response is [20038] withdrawal address is not valid

**Comment by godlikers** [comment]
sorry about that. coinType is "USDT-ERC20".
