### ISSUE TITLE
Cant place buy/sell orders with BIP/BTC, BIP/USDT

### ISSUE THREAD

**Issue by dinodigital** [bithumb-pro/bithumb.pro-official-api-docs#37]
Hello, Bithumb.

I cant place an order with tickers BIP/BTC and BIP/USDT. With other tickers everything works fine. But tickers list has BIP tickers and i can get market depth and other data. But i cant place buy/sell orders. 

Does api support BIP pairs?

**Comment by godlikers** [comment]
hi, api already support BIP pairs, pls check your request prams of place order

**Comment by dinodigital** [comment]
Nope. Still doesnt work. I've just placed buy order in pair BTC-USDT, but in BIP-USDT it returns "[20000] order params error". But i've changed just ticker, and price. Using Official Python SDK

This doesn't work
`bh = BithumbGlobalRestAPI(cfg['key'], cfg['secret'])
symbol = 'BIP-USDT'
side = 'sell'
price = 0.06713
amount = 1
print(bh.place_order(symbol, side, price, amount))
`

This works
`bh = BithumbGlobalRestAPI(cfg['key'], cfg['secret'])
symbol = 'BTC-USDT'
side = 'buy'
price = 9580
amount = 0.000104
print(bh.place_order(symbol, side, price, amount))
`

**Comment by dinodigital** [comment]
> hi, api already support BIP pairs, pls check your request prams of place order

Nope. Still doesnt work. I've just placed buy order in pair BTC-USDT, but in BIP-USDT it returns "[20000] order params error". But i've changed just ticker, and price. Using Official Python SDK

This doesn't work
```
bh = BithumbGlobalRestAPI(cfg['key'], cfg['secret'])
symbol = 'BIP-USDT'
side = 'sell'
price = 0.06713
amount = 1
print(bh.place_order(symbol, side, price, amount))
```

This works
```
bh = BithumbGlobalRestAPI(cfg['key'], cfg['secret'])
symbol = 'BTC-USDT'
side = 'buy'
price = 9580
amount = 0.000104
print(bh.place_order(symbol, side, price, amount))
```

**Comment by dinodigital** [comment]
This was because of the minimum order value – 700 BIP
Problem solved
