### ISSUE TITLE
Troubles with placing order

### ISSUE THREAD

**Issue by com-master** [bithumb-pro/bithumb.pro-official-api-docs#38]
Error code:[20044] quantity accuracy is wrong for placing order
Params: {'symbol': 'BTC-USDT', 'type': 'limit', 'side': 'sell', 'price': '9423.36', 'quantity': '0.00517446'}
Can you help me?

**Comment by godlikers** [comment]
hi, pls checkout your quantity accuracy for 'BTC-USDT', for now, this pairs's quantity accuracy is 6,  mean the correct quantity should be '0.005174'. you can use api 'https://github.com/bithumb-pro/bithumb.pro-official-api-docs/blob/master/rest-api.md#2-config-detail'

**Comment by com-master** [comment]
its very bad why you dont add this automatic in to you client? i will do pull requests
