### ISSUE TITLE
market order didn't work

### ISSUE THREAD

**Issue by proxychainio** [bithumb-pro/bithumb.pro-official-api-docs#4]
So many bugs... 
```
{"apiKey":"******","bizCode":"placeOrder","msgNo":"2596996162","price":"-1","quantity":"0.0015535","side":"buy","signature":"**********","symbol":"BTC-USDT","timestamp":"1563185756313","type":"market"}
```
always returns `20000下单参数错误`

**Comment by proxychainio** [comment]
`quantity` in market order means the the amount of quote? Your document didn't mention that at all.

**Comment by godlikers** [comment]
sorry,we had upgrade the doc,quantity in market order,means the amount of quote when side=buy.

**Comment by godlikers** [comment]
quantity must greater than or equal to the min trade amount, or will return 20000.
