### ISSUE TITLE
API ключи

### ISSUE THREAD

**Issue by kolyan7878** [bithumb-pro/bithumb.pro-official-api-docs#46]
Добрый день! Создал API ключ но он почему то не даёт удалённый доступ к торговле что нужно сделать?

**Comment by jopa22** [comment]
Пиши по английски

**Comment by kolyan7878** [comment]
Good afternoon! I created an API key but for some reason it does not give remote access to trading what should I do?

**Comment by kolyan7878** [comment]
Good afternoon! I created an API key, but for some reason it doesn't give remote access to trading, what should I do?

  
>Вторник, 28 июля 2020, 21:45 +03:00 от jopa22 <notifications@github.com>:
> 
> 
>Пиши по английски
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Николай Иванов
ivanovn_n@mail.ru
