### ISSUE TITLE
API

### ISSUE THREAD

**Issue by kolyan7878** [bithumb-pro/bithumb.pro-official-api-docs#47]
Good afternoon! I created an API key but for some reason it does not give remote access to trading what should I do?

**Comment by godlikers** [comment]
please check your api permission and ip whiteList on website.

**Comment by kolyan7878** [comment]
Where can I check the API resolution and whitelists? Something you have all very difficult!!!

  
>Среда, 29 июля 2020, 4:30 +03:00 от godlikers <notifications@github.com>:
> 
> 
>please check your api permission and ip whiteList on website.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Николай Иванов
ivanovn_n@mail.ru
