### ISSUE TITLE
Missing canceled order(spot) notification via websocket

### ISSUE THREAD

**Issue by proxychainio** [bithumb-pro/bithumb.pro-official-api-docs#7]
I've subscribed the private topic ORDER, when a order is canceled quickly(in 2 seconds), no updates received, I must use REST API to check if the order is canceled successfully or partially filled.

**Comment by godlikers** [comment]
this situation is happened frequently or occasionally？

**Comment by proxychainio** [comment]
occasionally

**Comment by godlikers** [comment]
maybe network delay, or connection had closed.actually you need to using REST API to check for this situation.

**Comment by proxychainio** [comment]
I can receive other order updates(filled order) at the same time, so connection is good.

**Comment by godlikers** [comment]
we will check for this.

**Comment by godlikers** [comment]
can you support the time when happened this situation.

**Comment by proxychainio** [comment]
08/01 08:09 order ID 85853551207682048
07/31 17:56 order ID 85638757817028608, 85638788331380736, 85638819456520192
07/31 17:54 order ID 85638234527272960, 85638266555768832, 85638298695929856,
07/25 14:08 order ID 83407054520250368, 83407086728310784, 83407119758393344

**Comment by godlikers** [comment]
the order id 85853551207682048 had been filled at that time.

**Comment by proxychainio** [comment]
check others

**Comment by godlikers** [comment]
we had check others and ws had pushed.

**Comment by proxychainio** [comment]
ok, I'll write some sample code to reproduce
